/**
 * Build the published documentation site.
 *
 * Every tag becomes a selectable version. Each tag's data is generated by the
 * generator that shipped *with that tag*, in its own worktree, so a version's
 * docs always match the tool that produced them — no mixing one release's
 * layout engine with another's config. The site itself is built once, from
 * `SITE_REF` (default: the latest non-prerelease tag), and that version is what
 * `/` serves.
 *
 * Run with `node --experimental-strip-types .github/scripts/deploy-docs.ts`.
 * Nothing here is type-checked; the annotations are for the reader.
 *
 * Environment:
 * - `SITE_REF`      ref to build the site from (default: latest stable tag).
 *                   `.` builds from the current checkout in place, which is
 *                   what a push to the default branch wants.
 * - `DOCS_BASE`     public base path, e.g. `lickle-docs` (default: none)
 * - `DOCS_OUT_DIR`  where the built site lands (default: `<workspace>/dist`)
 * - `GITHUB_WORKSPACE` repo root (default: the working directory)
 */
import { execFileSync } from 'node:child_process'
import { mkdirSync, readdirSync, copyFileSync, existsSync } from 'node:fs'
import path from 'node:path'

/** A git tag, which is also a version label and a URL segment. */
type Tag = string

const workspace: string = process.env['GITHUB_WORKSPACE'] ?? process.cwd()
const siteRef: string | undefined = process.env['SITE_REF']?.trim() || undefined
const base: string | undefined = process.env['DOCS_BASE']?.trim() || undefined
const outDir: string = process.env['DOCS_OUT_DIR'] ?? path.join(workspace, 'dist')

/** Per-tag `project.json` files, collected before the site is built. */
const dataDir: string = path.join(workspace, '.version-data')
/** One checkout per tag, so each can install and run its own tooling. */
const treeDir: string = path.join(workspace, '.worktrees')

// ─────────────────────────────────────────────────────────────────────────
// Shell and CI plumbing
// ─────────────────────────────────────────────────────────────────────────

const run = (cmd: string, args: string[], cwd: string = workspace): void => {
  console.log(`$ ${cmd} ${args.join(' ')}`)
  execFileSync(cmd, args, { cwd, stdio: 'inherit' })
}

const capture = (cmd: string, args: string[], cwd: string = workspace): string =>
  execFileSync(cmd, args, { cwd, encoding: 'utf8' }).trim()

/** Collapsible section in the Actions log. */
const group = <T>(title: string, fn: () => T): T => {
  console.log(`::group::${title}`)
  try {
    return fn()
  } finally {
    console.log('::endgroup::')
  }
}

const warn = (message: string): void => console.log(`::warning::${message}`)

// ─────────────────────────────────────────────────────────────────────────
// Versions
// ─────────────────────────────────────────────────────────────────────────

/**
 * Every tag, newest first. `-v:refname` is git's own version sort, so `0.0.10`
 * outranks `0.0.9` and prereleases sort below the release they precede — the
 * same ordering the version switcher applies to the data.
 */
const allTags = (): Tag[] =>
  capture('git', ['tag', '--list', '--sort=-v:refname'])
    .split('\n')
    .map((t) => t.trim())
    .filter(Boolean)

/**
 * The version the site leads with: the highest tag with no semver prerelease
 * suffix. Falls back to the highest tag, so a project with only prereleases
 * still publishes something, and finally to `HEAD` for a repo with no tags.
 */
const primaryRef = (tags: Tag[]): string =>
  siteRef ?? tags.find((t) => !t.includes('-')) ?? tags[0] ?? capture('git', ['rev-parse', 'HEAD'])

// ─────────────────────────────────────────────────────────────────────────
// Steps
// ─────────────────────────────────────────────────────────────────────────

/**
 * Check `ref` out into its own worktree and install its dependencies.
 *
 * `.` means the current checkout: build in place, with whatever is already
 * installed. A worktree of the ref you are already on would be a wasteful copy,
 * and it could not see uncommitted work.
 */
const prepare = (ref: string): string => {
  if (ref === '.') return workspace
  const tree = path.join(treeDir, ref)
  if (existsSync(path.join(tree, 'package.json'))) return tree
  // `--detach` so a ref already checked out elsewhere (the default branch,
  // typically) doesn't fail with "already used by worktree".
  run('git', ['worktree', 'add', '--detach', '--force', tree, ref])
  run('pnpm', ['install', '--frozen-lockfile', '--ignore-scripts'], tree)
  return tree
}

/**
 * Generate one tag's `project.json`, using that tag's own generator.
 *
 * Failures are reported and swallowed: an early release whose tooling predates
 * a flag simply doesn't appear in the switcher. One unbuildable tag must not
 * sink the deploy.
 */
const generate = (tag: Tag): boolean =>
  group(`Generate ${tag}`, () => {
    try {
      const tree = prepare(tag)
      run('pnpm', ['tsx', './src/cli.ts', 'generate', '--file', path.join(dataDir, `${tag}.json`)], tree)
      return true
    } catch {
      warn(`${tag}: could not generate docs data; omitting it from the version switcher`)
      return false
    }
  })

/**
 * Build the site from `ref`, with every other version's data alongside it.
 *
 * The primary's own file is excluded: it *is* the build, and the config would
 * otherwise list it in the switcher twice.
 */
const buildSite = (ref: string): void => {
  const tree = prepare(ref)
  const versions = path.join(tree, 'docs', 'version')
  mkdirSync(versions, { recursive: true })

  for (const file of existsSync(dataDir) ? readdirSync(dataDir) : []) {
    if (!file.endsWith('.json') || path.basename(file, '.json') === ref) continue
    // Skip the version this build already is, whatever ref named it.
    if (path.basename(file, '.json') === currentVersion(tree)) continue
    copyFileSync(path.join(dataDir, file), path.join(versions, file))
    console.log(`bundling version ${path.basename(file, '.json')}`)
  }

  const args = ['tsx', './src/cli.ts', 'build', '--static', '--outDir', outDir]
  if (base) args.push('--base', base)
  run('pnpm', args, tree)
}

/** The version this checkout will publish as, read from its package.json. */
const currentVersion = (tree: string): string => {
  try {
    return capture('node', ['-p', "require('./package.json').version"], tree)
  } catch {
    return ''
  }
}

// ─────────────────────────────────────────────────────────────────────────

const main = (): void => {
  mkdirSync(dataDir, { recursive: true })

  const tags = allTags()
  const primary = primaryRef(tags)

  if (!tags.length) warn('No tags found; publishing the current ref only.')
  console.log(`tags:    ${tags.join(', ') || '(none)'}`)
  console.log(`site:    ${primary}`)
  console.log(`outDir:  ${outDir}`)

  const built = tags.filter(generate)
  console.log(`generated ${built.length}/${tags.length} versions`)

  group(`Build site from ${primary}`, () => buildSite(primary))
}

main()
