/**
 * Build the published documentation site.
 *
 * Every stable release tag becomes a selectable version, generated by the
 * generator that shipped *with that tag*, in its own worktree — a version's
 * docs always match the tool that produced them. `--rev` adds any other
 * revision (a branch, a commit, a prerelease tag) to that list.
 *
 * The site itself is built once, from the newest stable release, and that
 * version is what `/` serves — unless that release's tooling is too old to
 * render the switcher, in which case the site is rebuilt from the current
 * checkout so the archived versions stay reachable.
 */
import * as cmd from 'cmd-ts'
import path from 'node:path'
import pc from 'picocolors'

import { build } from './build'

export const cli = cmd.command({
  name: 'build',
  description: 'Build the documentation site for every stable release',
  args: {
    workspace: cmd.option({
      description: 'The workspace directory',
      long: 'workspace',
      short: 'w',
      type: cmd.string,
      env: 'WORKSPACE',
      defaultValue: () => process.cwd(),
    }),
    outDir: cmd.option({
      description: 'Where the built site lands',
      long: 'out-dir',
      short: 'o',
      type: cmd.string,
      env: 'OUT_DIR',
      defaultValue: () => path.join(process.cwd(), 'dist'),
    }),
    base: cmd.option({
      description: 'Public base path, e.g. `/lickle-docs/`',
      long: 'base',
      short: 'b',
      type: cmd.string,
      env: 'BASE',
      defaultValue: () => '',
    }),
    revisions: cmd.option({
      description: 'Extra revisions to publish — tags, branches or commits, space separated',
      long: 'rev',
      short: 'r',
      type: cmd.string,
      env: 'REVISIONS',
      defaultValue: () => '',
    }),
    site: cmd.option({
      description: 'Revision to build the site from; `.` is the current checkout (default: newest stable release)',
      long: 'site',
      short: 's',
      type: cmd.optional(cmd.string),
      env: 'SITE',
    }),
  },
  handler: async (args) => build(args),
})
