/**
 * Build the published documentation site.
 *
 * Every stable release tag becomes a selectable version, generated by the
 * generator that shipped *with that tag*, in its own worktree — a version's
 * docs always match the tool that produced them. `--rev` adds any other
 * revision (a branch, a commit, a prerelease tag) to that list.
 *
 * The site itself is built once, from the newest stable release, and that
 * version is what `/` serves — unless that release's tooling is too old to
 * render the switcher, in which case the site is rebuilt from the current
 * checkout so the archived versions stay reachable.
 */
import { existsSync, promises as fs } from 'node:fs'
import * as semver from 'semver'
import * as cmd from 'cmd-ts'
import path from 'node:path'
import pc from 'picocolors'
import { $ } from 'execa'

const cli = cmd.command({
  name: 'build',
  description: 'Build the documentation site for every stable release',
  args: {
    workspace: cmd.option({
      description: 'The workspace directory',
      long: 'workspace',
      short: 'w',
      type: cmd.string,
      env: 'WORKSPACE',
      defaultValue: () => process.cwd(),
    }),
    outDir: cmd.option({
      description: 'Where the built site lands',
      long: 'out-dir',
      short: 'o',
      type: cmd.string,
      env: 'OUT_DIR',
      defaultValue: () => path.join(process.cwd(), 'dist'),
    }),
    base: cmd.option({
      description: 'Public base path, e.g. `/lickle-docs/`',
      long: 'base',
      short: 'b',
      type: cmd.string,
      env: 'BASE',
      defaultValue: () => '',
    }),
    revisions: cmd.option({
      description: 'Extra revisions to publish — tags, branches or commits, space separated',
      long: 'rev',
      short: 'r',
      type: cmd.string,
      env: 'REVISIONS',
      defaultValue: () => '',
    }),
    site: cmd.option({
      description: 'Revision to build the site from; `.` is the current checkout (default: newest stable release)',
      long: 'site',
      short: 's',
      type: cmd.optional(cmd.string),
      env: 'SITE',
    }),
  },
  handler: async (args) => {
    // The site build runs inside a worktree, so `outDir` must not be relative.
    const outDir = path.resolve(args.outDir)
    const workspace = path.resolve(args.workspace)
    const ctx: Ctx = {
      workspace,
      treeDir: path.join(workspace, '.worktrees'),
      dataDir: path.join(workspace, '.version-data'),
    }
    await ensureDir(ctx.dataDir)

    const releases = (await gitTags(ctx)).filter(stable).sort(byVersionDesc)
    const extra = words(args.revisions)

    // `blank` because CI passes these through, and an unset input arrives as an
    // empty string — which `??` would happily accept as a revision.
    const chosen = blank(args.site)
    const primary = chosen ?? releases[0] ?? extra[0] ?? '.'
    // Everything the switcher can offer: the extras plus every stable release.
    const candidates = uniq([...extra, ...releases])

    log.info(`outDir   ${pc.cyan(outDir)}`)

    const plan: Plan = { ctx, candidates, outDir, base: args.base }
    if (await deploy(plan, primary)) return log.done(`site built from ${primary}`)

    // An explicit `--site` is the caller's call to make, and the checkout is
    // already the newest tooling there is — neither has anywhere to fall back to.
    if (chosen || primary === '.') {
      log.warn(
        `${primary} produced no version switcher, so the other versions are not reachable. ` +
          `Its tooling predates multi-version support — build from a newer revision (SITE=.).`,
      )
      return log.done(`site built from ${primary}`)
    }

    log.warn(
      `${primary} produced no version switcher — its tooling predates multi-version support. ` +
        `Rebuilding from the current checkout so the other versions stay reachable; pass SITE to override.`,
    )
    // Vite empties `outDir` itself, but only when it owns the directory; the
    // site is built from a worktree, so clear the first attempt by hand.
    await fs.rm(outDir, { recursive: true, force: true })
    if (!(await deploy(plan, '.'))) log.warn('the current checkout produced no version switcher either')
    log.done('site built from the current checkout')
  },
})

type Ctx = { workspace: string; treeDir: string; dataDir: string }
type Plan = { ctx: Ctx; candidates: string[]; outDir: string; base: string }

// ─────────────────────────────────────────────────────────────────────────
// Steps
// ─────────────────────────────────────────────────────────────────────────

/**
 * Generate one revision's `project.json`, using that revision's own generator.
 * A tag's data never changes, so an existing file is reused.
 *
 * Failures are reported and swallowed: an early release whose tooling predates
 * a flag simply doesn't appear in the switcher. One unbuildable revision must
 * not sink the deploy.
 */
const generate = async (ctx: Ctx, rev: string): Promise<boolean> => {
  const file = dataFile(ctx, rev)
  if (existsSync(file)) {
    log.done(`${rev} cached`)
    return true
  }

  return group(`Generate ${rev}`, async () => {
    try {
      await runIn(ctx, rev, (cwd) => sh(cwd)`pnpm tsx ./src/cli.ts generate --file ${file}`)
      await label(file, rev)
      log.done(`${rev} generated`)
      return true
    } catch {
      log.warn(`${rev}: could not generate docs data; omitting it from the version switcher`)
      return false
    }
  })
}

/**
 * Name a revision's data after the revision, unless it is a release tag.
 *
 * A branch or commit build carries whatever version its `package.json` had, so
 * `main` and `a1b2c3` from the same line both claim e.g. `0.0.2-dev.3`. The
 * switcher dedupes by version, so they would silently collapse into one entry —
 * or into the site's own. Labelling them by revision keeps each distinct and
 * says something useful in the dropdown.
 */
const label = async (file: string, rev: string): Promise<void> => {
  if (semver.valid(rev)) return
  const json = JSON.parse(await fs.readFile(file, 'utf8')) as { version?: string }
  json.version = rev
  await fs.writeFile(file, JSON.stringify(json))
}

/**
 * Build the whole site with `primary` at `/`, and report whether the result
 * actually offers the other versions.
 *
 * The switcher is rendered by whichever revision the site is built *from*, so a
 * `primary` whose tooling predates multi-version support quietly drops every
 * archived version: the build succeeds and the result looks like a one-version
 * site. Returning that as a value lets the caller rebuild from newer tooling
 * rather than publish a site missing its own history.
 */
const deploy = async (p: Plan, primary: string): Promise<boolean> => {
  // Everything the switcher offers, minus whatever the site is built from —
  // that one *is* the build.
  const versions = p.candidates.filter((r) => r !== primary)

  // List the site among the versions: it is the one served at `/`, and
  // reporting only the *others* reads as though it were the only one built.
  log.info(`site     ${pc.cyan(primary)} ${pc.dim('→ /')}`)
  log.info(`versions ${pc.cyan([primary, ...versions].join(', '))}`)
  // The site's own version is what `/` serves and what the switcher shows as
  // current, so leading with anything but a release is worth saying out loud.
  if (!stable(primary))
    log.warn(
      primary === '.'
        ? 'the site is built from the current checkout, not a release; readers will land on unreleased docs'
        : `${primary} is not a stable release; readers will land on it by default`,
    )

  const built: string[] = []
  for (const rev of versions) if (await generate(p.ctx, rev)) built.push(rev)
  if (versions.length) log.info(`archived ${pc.green(`${built.length}`)}/${versions.length} generated`)

  await group(`Build site from ${primary}`, () =>
    buildSite(p.ctx, { primary, built, outDir: p.outDir, base: p.base }),
  )

  // Nothing was archived, so there is nothing for a switcher to reach.
  if (!built.length) return true
  const files = await fs.readdir(p.outDir, { recursive: true })
  return files.some((f) => /project-.*\.json$/.test(String(f)))
}

/** Build the site from `primary`, with every other version's data alongside it. */
const buildSite = (ctx: Ctx, p: { primary: string; built: string[]; outDir: string; base: string }): Promise<void> =>
  runIn(ctx, p.primary, async (cwd) => {
    // The site's config globs this directory, so it must hold exactly the
    // versions this build archived — not the leftovers of an earlier one. It is
    // generated and gitignored, so the script owns it outright.
    const versions = path.join(cwd, 'docs', 'version')
    await fs.rm(versions, { recursive: true, force: true })
    await ensureDir(versions)

    for (const rev of p.built) {
      await fs.copyFile(dataFile(ctx, rev), path.join(versions, `${slug(rev)}.json`))
      log.info(`bundling version ${pc.cyan(rev)}`)
    }

    const base = p.base ? ['--base', p.base] : []
    await sh(cwd)`pnpm tsx ./src/cli.ts build --static --outDir ${p.outDir} ${base}`
  })

// ─────────────────────────────────────────────────────────────────────────
// Git
// ─────────────────────────────────────────────────────────────────────────

const gitTags = async (ctx: Ctx): Promise<string[]> =>
  words(await capture(ctx.workspace)`git tag --list --sort=-v:refname`)

/**
 * Check `rev` out into its own worktree, install its dependencies, and run `f`
 * there. An existing worktree is reused; the current checkout is used in place.
 */
const runIn = async <T>(ctx: Ctx, rev: string, f: (cwd: string) => Promise<T>): Promise<T> => {
  if (!rev.trim()) throw new Error('Cannot check out an empty revision')
  if (rev === '.') return f(ctx.workspace)
  const cwd = path.join(ctx.treeDir, slug(rev))
  if (existsSync(path.join(cwd, 'package.json'))) return f(cwd)

  await ensureDir(ctx.treeDir)
  // `--detach` so a ref already checked out elsewhere doesn't fail with
  // "already used by worktree".
  await sh(ctx.workspace)`git worktree add --detach --force ${cwd} ${rev}`
  await sh(cwd)`pnpm install --frozen-lockfile --ignore-scripts`
  return f(cwd)
}

// ─────────────────────────────────────────────────────────────────────────
// Plumbing
// ─────────────────────────────────────────────────────────────────────────

/** Run a command, streaming its output. The result's stdout is not captured. */
const sh = (cwd: string) => {
  const exec = $({ cwd, stdin: 'ignore', stdout: 'inherit', stderr: 'inherit' })
  return (strings: TemplateStringsArray, ...values: unknown[]) => {
    log.cmd(text(strings, values), cwd)
    return exec(strings, ...(values as never[]))
  }
}

/**
 * Run a command and return its stdout, echoing it so the log still shows it.
 *
 * Kept separate from {@link sh} deliberately. Teeing one stream to both a pipe
 * and the terminal (`stdout: ['pipe', 'inherit']`) proved unreliable on the CI
 * runner: `git tag` printed its tags but the capture came back empty. Anything
 * read as a *value* gets a plain pipe.
 */
const capture = (cwd: string) => {
  const exec = $({ cwd, stdin: 'ignore', stdout: 'pipe', stderr: 'inherit' })
  return async (strings: TemplateStringsArray, ...values: unknown[]): Promise<string> => {
    log.cmd(text(strings, values), cwd)
    const { stdout } = await exec(strings, ...(values as never[]))
    const out = typeof stdout === 'string' ? stdout : ''
    if (out) console.log(out)
    return out
  }
}

const text = (strings: TemplateStringsArray, values: unknown[]): string =>
  strings.raw.reduce((acc, s, i) => acc + flat(values[i - 1] ?? '') + s, '').replace(/\s+/g, ' ').trim()

const flat = (v: unknown): string => (Array.isArray(v) ? v.join(' ') : String(v))

/** Collapsible section in the Actions log; a plain heading elsewhere. */
const group = async <T>(title: string, f: () => Promise<T>): Promise<T> => {
  console.log(ci ? `::group::${title}` : pc.bold(pc.magenta(`\n▸ ${title}`)))
  try {
    return await f()
  } finally {
    if (ci) console.log('::endgroup::')
  }
}

const ci = !!process.env['GITHUB_ACTIONS']

const log = {
  info: (m: string) => console.log(`${pc.dim('·')} ${m}`),
  cmd: (c: string, cwd: string) => console.log(pc.dim(`$ ${c}  ${pc.italic(`(${path.basename(cwd)})`)}`)),
  done: (m: string) => console.log(`${pc.green('✔')} ${m}`),
  warn: (m: string) => console.log(ci ? `::warning::${m}` : `${pc.yellow('!')} ${m}`),
}

const stable = (rev: string): boolean => !!semver.valid(rev) && !semver.prerelease(rev)
const byVersionDesc = (a: string, b: string) => semver.compare(b, a)
const uniq = <T>(xs: T[]): T[] => Array.from(new Set(xs))
/** Split a whitespace- or comma-separated list, dropping blanks. */
const words = (s: string): string[] => s.split(/[\s,]+/).map((x) => x.trim()).filter(Boolean)
/** Trim an option, treating an empty or whitespace-only value as absent. */
const blank = (s: string | undefined): string | undefined => (s?.trim() ? s.trim() : undefined)
/** Filesystem-safe name for a revision — `feat/x` and `a1b2c3` both need one. */
const slug = (rev: string): string => rev.replace(/[^\w.-]+/g, '-')
const dataFile = (ctx: Ctx, rev: string) => path.join(ctx.dataDir, `${slug(rev)}.json`)
const ensureDir = (dir: string) => fs.mkdir(dir, { recursive: true })

cmd.run(cli, process.argv.slice(2)).catch((err) => {
  console.error(pc.red(err?.message ?? err))
  process.exit(1)
})
