name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          version: 10
      - uses: actions/setup-node@v6

      - name: install dependencies
        run: pnpm install
      - name: transpile typescript
        run: pnpm build
      - name: test
        run: pnpm test
